---
version: "3.8"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auction_dev
      - POSTGRES_USER=auction
      - POSTGRES_PASSWORD=s3cr3t

volumes:
  postgres-data:
